project:
  type: website
  output-dir: docs
  
editor: 
  mode: source

website:
  title: "COSSEE Coding Club"
  favicon: icons/temp_logo.png
  sidebar:
    title: "COSSEE Coding Club (COSSEE-CC)"
    logo: icons/cossee_logo.png
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Welcome to COSSEE Coding Club
      - text: "<b>Autumn 2026 Table of Contents</b>"
      - href: pages/sept-14-using-r-and-git-ejl.qmd
        text: "September 14th: Using R and Git"
      - href: pages/sept-28-julia-sn.qmd
        text: "September 28th: Julia with Shinichi"
format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
